In [1]:
import numpy as np

#Ejercicios Clase 7

##Investigar y ejemplificar diferencias entre np.array y np.matrix

Las matrices de numpy son conjuntos extrictamente bidimensionales pero que tienen ciertas ventajas sobre arrays: A Ambos metodos se les puede aplicar **.T** para obtener su transpuesta, sin embargo las matrices poseen el .h para la transpuesta conjugada y .I para la invertidad. Lo que significa que podemos tener mayor flexibilidad a la forma de multiplicar los elementos element-wise.

De acuaerdo a la documetación oficial de Numpy, las matrices serán deprecadas en futuras versiones por lo que no es recomendado utilizarlas.

Cuando utilizamos un array de 2 dimensiones son extrictamente lo mismo por lo que la posible redundancia del metodo lleva a su posible deprecación


#Ejercicios Clase 8
**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [12]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [25]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print("H1= \n",H1)
print("OL= \n", OL)

H1= 
 [[0.52472981 0.88079708]
 [0.72908792 1.        ]]
OL= 
 [[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [57]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [58]:

def neural_network(X):
  H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])
  
  OL_W = np.array([0.116,0.329,0.708])

  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  return OL


In [59]:
xa=np.array([[1,1]])
neural_network(xa)

array([0.69269553])

In [60]:
xb = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
neural_network(xb)

array([0.70244573, 0.66259284, 0.75933678, 0.75973948, 0.75802295,
       0.6739704 , 0.75954693, 0.76005845, 0.75952743, 0.76005845])

In [61]:
def ReLu(x): #convertir los valores de x al rango de 0 a 1
    
    return np.maximum(x, 0)

def neural_network_relu(X):
  H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])
  
  OL_W = np.array([0.116,0.329,0.708])

  H1 = np.matmul(X,H1_W)
  H1 = ReLu(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  OL = ReLu(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  return OL

In [62]:
xc = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
neural_network_relu(xc)

array([1.2901751e+00, 3.9827325e-01, 7.5763340e+00, 8.4233580e+00,
       5.8520720e+00, 6.1724410e-01, 7.7977270e+00, 1.6403930e+02,
       7.7289650e+00, 1.0551858e+03])